import assert from "node:assert/strict";
import test from "node:test";
import { readFile, readdir, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const plugin = join(root, "plugins/test-lab");
const json = async path => JSON.parse(await readFile(path, "utf8"));

test("Marketplace contains one version-consistent legacy plugin and an extension container", async () => {
  const marketplace = await json(join(root, ".github/plugin/marketplace.json"));
  const manifest = await json(join(plugin, "plugin.json"));
  assert.equal(marketplace.name, "testing-marketplace");
  assert.equal(marketplace.plugins.length, 1);
  assert.equal(marketplace.plugins[0].source, "./plugins/test-lab");
  assert.equal(marketplace.plugins[0].name, "test-lab");
  assert.equal(manifest.name, "test-lab");
  assert.equal(manifest.version, marketplace.plugins[0].version);
  assert.equal(manifest.version, (await json(join(root, "package.json"))).version);
  assert.equal(manifest.$schema, undefined);
  assert.deepEqual(manifest.extensions, ["./extensions"]);
  assert.equal((await stat(join(plugin, "extensions/test-dashboard/extension.mjs"))).isFile(), true);
});

test("Only shared Context7 is active; the Azure example cannot be mistaken for active MCP config", async () => {
  const mcp = await json(join(plugin, ".mcp.json"));
  assert.deepEqual(Object.keys(mcp.mcpServers), ["test-lab-context7"]);
  assert.deepEqual(mcp.mcpServers["test-lab-context7"], {
    type: "http", url: "https://mcp.context7.com/mcp", tools: ["resolve-library-id", "query-docs"],
  });
  const example = await json(join(plugin, "config/playwright-workspace.example.json"));
  assert.equal(example.exampleOnly, true);
  assert.equal(example.mcpServers, undefined);
  assert.equal(example.headers, undefined);
  assert.equal(example.url, undefined);
});

test("Consumer assets are self-contained, licensed, text-safe and SDK-external", async () => {
  const extension = join(plugin, "extensions/test-dashboard");
  const entry = await readFile(join(extension, "extension.mjs"), "utf8");
  assert.match(entry, /from "@github\/copilot-sdk\/extension"/);
  const bundle = await readFile(join(extension, "lib/test-lab.mjs"), "utf8");
  assert.doesNotMatch(bundle, /from ["'](?:fast-xml-parser|typescript|@github\/copilot-sdk)/);
  assert.ok(bundle.length > 1000);
  const notices = await readFile(join(plugin, "THIRD_PARTY_NOTICES.txt"), "utf8");
  assert.match(notices, /fast-xml-parser@5\.11\.1/);
  assert.match(notices, /Copyright/);
  const renderer = await readFile(join(extension, "public/app.js"), "utf8");
  assert.doesNotMatch(renderer, /innerHTML|outerHTML|insertAdjacentHTML|document\.write|\beval\s*\(/);
  const files = await readdir(plugin);
  assert.ok(!files.includes("node_modules") && !files.includes("package.json"));
});

test("Agent inherits model and grants only explicit hosted browser methods", async () => {
  const agent = await readFile(join(plugin, "agents/test-lab-engineer.agent.md"), "utf8");
  const frontmatter = agent.split("---")[1];
  assert.match(frontmatter, /name: Test Engineer/);
  assert.doesNotMatch(frontmatter, /^model:/m);
  assert.doesNotMatch(frontmatter, /\*|browser_run_code|browser_evaluate|screenshot|file_upload/);
  assert.match(frontmatter, /test-lab-playwright\/create_browser_session/);
  assert.match(frontmatter, /test-lab-playwright\/close_browser_session/);
  assert.match(frontmatter, /test-lab-context7\/resolve-library-id/);
  assert.match(frontmatter, /test-lab-context7\/query-docs/);
  assert.doesNotMatch(frontmatter, /\btask\b|run_factory|create_session/);
});

test("Synthetic producer fixture contains no machine-specific paths or opaque run folders", async () => {
  const fixture = await readFile(join(root, "tests/fixtures/playwright-junit.xml"), "utf8");
  assert.doesNotMatch(fixture, /\/(?:Users|home|private|var\/folders)\//);
  assert.doesNotMatch(fixture, /test-lab-producer-[A-Za-z0-9]{6}/);
  assert.match(fixture, /Generated by @playwright\/test/);
});
