import { build } from "esbuild";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const plugin = join(root, "plugins/test-lab");
const output = join(plugin, "extensions/test-dashboard/lib/test-lab.mjs");
const result = await build({
  absWorkingDir: root,
  entryPoints: ["src/runtime.ts"],
  outfile: output,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "inline",
  write: false,
  metafile: true,
  banner: { js: "// Generated by npm run build. Do not edit. The Copilot SDK is host-provided." },
});
const packages = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!input.startsWith("node_modules/")) continue;
  const parts = input.slice("node_modules/".length).split("/");
  const name = parts[0].startsWith("@") ? parts.slice(0, 2).join("/") : parts[0];
  if (name === "@github/copilot-sdk") throw new Error("The host SDK must never be bundled.");
  packages.add(name);
}
const notices = ["Third-party licenses for the generated Test Lab bundle.\nReproduce with npm ci --ignore-scripts && npm run build.\n"];
for (const name of [...packages].sort()) {
  const directory = resolve(root, "node_modules", name);
  const pkg = JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
  const licenses = (await readdir(directory)).filter(file => /^(?:license|copying)(?:\.[a-z]+)?$/i.test(file)).sort();
  notices.push(`\n===== ${name}@${pkg.version} (${pkg.license}) =====\n`);
  if (!licenses.length && name === "@nodable/entities" && pkg.version === "3.0.0") {
    notices.push("License omitted by npm tarball; preserved from its published gitHead:\nhttps://github.com/nodable/val-parsers/blob/d2070d76a8ba07e6c7fa142caeb51ffd756e47eb/LICENSE\n");
    notices.push(await readFile(join(root, "scripts/licenses/nodable-entities-MIT.txt"), "utf8"));
  } else if (!licenses.length) throw new Error(`No license file found for bundled package ${name}.`);
  for (const file of licenses) notices.push(await readFile(join(directory, file), "utf8"));
}
await mkdir(dirname(output), { recursive: true });
for (const file of result.outputFiles) await writeFile(file.path, file.contents);
await writeFile(join(plugin, "THIRD_PARTY_NOTICES.txt"), notices.join("\n"));
await writeFile(join(plugin, "LICENSE"), await readFile(join(root, "LICENSE")));
console.info(`Built ${result.outputFiles[0].contents.length} bytes; bundled ${packages.size} licensed dependencies; no SDK or consumer install.`);
